# Generated by Django 2.2.3 on 2020-06-27 21:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CampaingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=350)),
                ('desc', models.CharField(max_length=350)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questo', to='CampaingApp.Campaing')),
            ],
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
    ]
