# Generated by Django 2.2.3 on 2020-07-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampaingApp', '0003_pj_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='participants',
            field=models.ManyToManyField(to='CampaingApp.Pj'),
        ),
    ]
