# Generated by Django 2.2.3 on 2020-07-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampaingApp', '0004_quest_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Userino', to=settings.AUTH_USER_MODEL),
        ),
    ]
