# Generated by Django 2.2.3 on 2020-07-05 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampaingApp', '0006_auto_20200705_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pjota', to=settings.AUTH_USER_MODEL),
        ),
    ]
